### ISSUE TITLE
Failed to compile on macOS 10.15

### ISSUE THREAD

**Issue by hellotanuky** [ungoogled-software/ungoogled-chromium-macos#31]
ungoogled-chromium tag: 77.0.3865.90-1
OS: macOS 10.15
Xcode 11.2 beta 2

```
In file included from gen/chrome/browser/ui/ui_jumbo_mm.mm:52:
./../../chrome/browser/ui/cocoa/renderer_context_menu/render_view_context_menu_mac_cocoa.mm:101:42: error: too many arguments to function call, expected 0, have 5
  g_original_populatemenu_implementation(self, _cmd, menu, remainingEntries,
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

In file included from gen/chrome/browser/browser_jumbo_mm.mm:5:
./../../chrome/browser/app_controller_mac.mm:317:60: error: too many arguments to function call, expected 0, have 5
  g_swizzle_imk_input_session->GetOriginalImplementation()(self, _cmd, range,
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~
```

If I pass `-DOBJC_OLD_DISPATCH_PROTOTYPES` flag to the compiler, this error no longer occurs. However another error jumped out:
```
[1583/1739] ACTION //tools/v8_context_snapshot:generate_v8_context_snapshot(//build/toolchain/mac:clang_x64)
FAILED: v8_context_snapshot.bin
python ../../build/gn_run_binary.py ./v8_context_snapshot_generator --output_file=v8_context_snapshot.bin
./v8_context_snapshot_generator failed with exit code -5
ninja: build stopped: subcommand failed.
```

**Comment by hellotanuky** [comment]
I tried to compile the latest official Chrome dev version `79.0.3938.0` and got the same error.

**Comment by hellotanuky** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1014063
https://bugs.chromium.org/p/chromium/issues/detail?id=973128
Chromium does not support building with 10.15 SDK.

But there are still bugs related to 10.14 SDK...
https://bugs.chromium.org/p/chromium/issues/detail?id=943106

**Comment by hellotanuky** [comment]
See [crbug](https://bugs.chromium.org/p/chromium/issues/detail?id=973128&can=1&q=10.15%20sdk&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified) Chromium already supports building with Xcode 11 in master branch. I tried version 80+ and build succeeded. I didn't check changelogs so I don't know from which specific version number Xcode 11 is supported....

**Comment by Eloston** [comment]
Cool, I guess we can close this once Chromium 80 comes out.

**Comment by r1sim** [comment]
I successfully built chromium 80 on catalina using the tag `80.0.3987.87-2.1`.

**Comment by Eloston** [comment]
Closing because 80 is out.
